/**
 * @author nttdocomo
 */
var http = require("http"), fs = require('fs'), cheerio = require('cheerio'),excute = require('../transfermarkt.co.uk/excute'),StringDecoder = require('string_decoder').StringDecoder,mysql = require('mysql'),moment = require('moment'),moment_tz = require('moment-timezone'),
Crawler = require("simplecrawler"),pool  = require('../transfermarkt.co.uk/pool'),get_seasons = require('./get_seasons'),
input_url = process.argv[2],
host = 'http://www.whoscored.com';
_ = require('underscore');
crawler = new Crawler('www.whoscored.com');
crawler.maxConcurrency = 2;
crawler.interval = 500;
crawler.timeout = 5000;
crawler.discoverResources = false;
crawler.userAgent = 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36';
crawler.customHeaders = {
    Host:'www.whoscored.com',
    Referer:'http://www.whoscored.com/LiveScores',
    'X-Requested-With':'XMLHttpRequest',
    Cookie:'__gads=ID=7400c9eb48861252:T=1407717687:S=ALNI_MZbNZufnguyMAdt6A2DXy8Hirg7oA; ebNewBandWidth_.www.whoscored.com=863%3A1408183698417; ui=nttdocomo:bjmU8NSBC0WzoKOkAO-9TQ:3619521175:SHKLWvTkwNCw4YKgZQA0cg8IkHCbOnpSkXIJdsjHZI8; ua=nttdocomo:bjmU8NSBC0WzoKOkAO-9TQ:3619521175:Cmahf0NIXa_v-sD8BkI3Tg9HVIkTt2NruY5jcRetDrM; mp_430958bdb5bff688df435b09202804d9_mixpanel=%7B%22distinct_id%22%3A%20%22147c283461b55-0841a221e-4e46072c-1fa400-147c283461d11f%22%2C%22%24initial_referrer%22%3A%20%22http%3A%2F%2Fwww.whoscored.com%2F%22%2C%22%24initial_referring_domain%22%3A%20%22www.whoscored.com%22%7D; _ga=GA1.2.458243098.1407717765'
};
crawler.on("fetchcomplete",function(queueItem, responseBuffer, response){
    var decoder = new StringDecoder('utf8');
    //console.log(decoder.write(responseBuffer));
    if(/^\/Regions\/\d{1,3}\/Tournaments\/\d{1,6}\/[a-zA-Z\-]{1,}$/.test(queueItem.path)){
        var stageId = /stageId\:\s(\d{1,})/.exec(decoder.write(responseBuffer))[1],
        seasons = get_seasons(cheerio.load(decoder.write(responseBuffer)));
        console.log(stageId)
    }
}).on('fetchstart',function(queueItem , requestOptions){
    /*if(/^\/MatchesFeed\/(\d{1,})\/MatchCentre2$/.test(queueItem.path)){
        requestOptions.headers.Referer = 'http://www.whoscored.com/Matches/'+queueItem.path.replace(/^\/MatchesFeed\/(\d{1,})\/MatchCentre2$/,"$1")+'/Live';
    } else {
        requestOptions.headers.Referer = 'http://www.whoscored.com/LiveScores';
    }*/
}).on('complete',function(){
    console.log('complete')
}).on('fetcherror',function(queueItem, response){
    console.log('fetcherror')
}).on('fetchtimeout',function(queueItem, response){
    crawler.queueURL(host + queueItem.path);
    console.log('fetchtimeout:' + queueItem.path)
}).on('fetchclienterror',function(queueItem, errorData){
    crawler.queueURL(host + queueItem.path);
    console.log('fetchclienterror')
});
var allRegions = [{type:1, id:248, flg:'flg-caf', name: 'Africa', tournaments: [{id:290, url:'/Regions/248/Tournaments/290/Africa-CAF-Champions-League', name:'CAF Champions League'},{id:573, url:'/Regions/248/Tournaments/573/Africa-', name:''},{id:574, url:'/Regions/248/Tournaments/574/Africa-', name:''},{id:505, url:'/Regions/248/Tournaments/505/Africa-CECAFA-Senior-Challenge-Cup', name:'CECAFA Senior Challenge Cup'}]},
{type:0, id:3, flg:'flg-al', name: 'Albania', tournaments: [{id:406, url:'/Regions/3/Tournaments/406/Albania-1-Division', name:'1. Division'},{id:182, url:'/Regions/3/Tournaments/182/Albania-Kategoria-Superiore', name:'Kategoria Superiore'},{id:451, url:'/Regions/3/Tournaments/451/Albania-Kategoria-Superiore-qualification', name:'Kategoria Superiore qualification'}]},
{type:0, id:4, flg:'flg-dz', name: 'Algeria', tournaments: [{id:281, url:'/Regions/4/Tournaments/281/Algeria-Championnat-National', name:'Championnat National'},{id:518, url:'/Regions/4/Tournaments/518/Algeria-', name:''}]},
{type:0, id:6, flg:'flg-ad', name: 'Andorra', tournaments: [{id:142, url:'/Regions/6/Tournaments/142/Andorra-1-Division', name:'1. Division'},{id:397, url:'/Regions/6/Tournaments/397/Andorra-2-Division', name:'2. Division'},{id:526, url:'/Regions/6/Tournaments/526/Andorra-', name:''}]},
{type:0, id:7, flg:'flg-ao', name: 'Angola', tournaments: [{id:245, url:'/Regions/7/Tournaments/245/Angola-1-Division', name:'1. Division'}]},
{type:0, id:10, flg:'flg-ag', name: 'Antigua and Barbuda', tournaments: [{id:378, url:'/Regions/10/Tournaments/378/Antigua-and-Barbuda-Premier-Division', name:'Premier Division'}]},
{type:0, id:11, flg:'flg-ar', name: 'Argentina', tournaments: [{id:68, url:'/Regions/11/Tournaments/68/Argentina-Primera-Divisin', name:'Primera División'},{id:317, url:'/Regions/11/Tournaments/317/Argentina-Primera-B-Nacional', name:'Primera B Nacional'},{id:489, url:'/Regions/11/Tournaments/489/Argentina-', name:''},{id:504, url:'/Regions/11/Tournaments/504/Argentina-', name:''},{id:541, url:'/Regions/11/Tournaments/541/Argentina-', name:''},{id:463, url:'/Regions/11/Tournaments/463/Argentina-Primera-B-Metropolitana', name:'Primera B Metropolitana'},{id:450, url:'/Regions/11/Tournaments/450/Argentina-Primera-B-Nacional-Qualification', name:'Primera B Nacional - Qualification'}]},
{type:0, id:12, flg:'flg-am', name: 'Armenia', tournaments: [{id:156, url:'/Regions/12/Tournaments/156/Armenia-Premier-League', name:'Premier League'},{id:256, url:'/Regions/12/Tournaments/256/Armenia-Cup', name:'Cup'},{id:270, url:'/Regions/12/Tournaments/270/Armenia-Super-Cup', name:'Super Cup'}]},
{type:1, id:249, flg:'flg-cas', name: 'Asia Pacific', tournaments: [{id:287, url:'/Regions/249/Tournaments/287/Asia-Pacific-AFC-Champions-League', name:'AFC Champions League'},{id:212, url:'/Regions/249/Tournaments/212/Asia-Pacific-East-Asian-Championship', name:'East Asian Championship'},{id:241, url:'/Regions/249/Tournaments/241/Asia-Pacific-Gulf-Cup', name:'Gulf Cup'},{id:490, url:'/Regions/249/Tournaments/490/Asia-Pacific-', name:''},{id:575, url:'/Regions/249/Tournaments/575/Asia-Pacific-', name:''},{id:576, url:'/Regions/249/Tournaments/576/Asia-Pacific-', name:''}]},
{type:0, id:14, flg:'flg-au', name: 'Australia', tournaments: [{id:194, url:'/Regions/14/Tournaments/194/Australia-A-League', name:'A-League'},{id:312, url:'/Regions/14/Tournaments/312/Australia-Australia-2', name:'Australia 2'},{id:567, url:'/Regions/14/Tournaments/567/Australia-', name:''},{id:577, url:'/Regions/14/Tournaments/577/Australia-', name:''}]},
{type:0, id:15, flg:'flg-at', name: 'Austria', tournaments: [{id:32, url:'/Regions/15/Tournaments/32/Austria-T-Mobile-Bundesliga', name:'T-Mobile Bundesliga'},{id:53, url:'/Regions/15/Tournaments/53/Austria-Erste-Liga', name:'Erste Liga'},{id:90, url:'/Regions/15/Tournaments/90/Austria-Playoff', name:'Playoff'},{id:83, url:'/Regions/15/Tournaments/83/Austria-Stiegl-Cup', name:'Stiegl Cup'},{id:93, url:'/Regions/15/Tournaments/93/Austria-T-Mobile-Super-Cup', name:'T-Mobile Super Cup'},{id:441, url:'/Regions/15/Tournaments/441/Austria-Regionalliga', name:'Regionalliga'},{id:440, url:'/Regions/15/Tournaments/440/Austria-Wienerliga', name:'Wienerliga'}]},
{type:0, id:16, flg:'flg-az', name: 'Azerbaijan', tournaments: [{id:173, url:'/Regions/16/Tournaments/173/Azerbaijan-Premier-League', name:'Premier League'},{id:409, url:'/Regions/16/Tournaments/409/Azerbaijan-1-Division', name:'1. Division'}]},
{type:0, id:18, flg:'flg-bh', name: 'Bahrain', tournaments: [{id:302, url:'/Regions/18/Tournaments/302/Bahrain-1-Division', name:'1. Division'}]},
{type:0, id:20, flg:'flg-bb', name: 'Barbados', tournaments: [{id:370, url:'/Regions/20/Tournaments/370/Barbados-Premier-Division', name:'Premier Division'}]},
{type:0, id:21, flg:'flg-by', name: 'Belarus', tournaments: [{id:157, url:'/Regions/21/Tournaments/157/Belarus-Premier-League', name:'Premier League'},{id:480, url:'/Regions/21/Tournaments/480/Belarus-', name:''}]},
{type:0, id:22, flg:'flg-be', name: 'Belgium', tournaments: [{id:18, url:'/Regions/22/Tournaments/18/Belgium-Jupiler-League', name:'Jupiler League'},{id:28, url:'/Regions/22/Tournaments/28/Belgium-Cup', name:'Cup'},{id:117, url:'/Regions/22/Tournaments/117/Belgium-Super-Cup', name:'Super Cup'},{id:137, url:'/Regions/22/Tournaments/137/Belgium-Second-Division', name:'Second Division'},{id:161, url:'/Regions/22/Tournaments/161/Belgium-Play-Off', name:'Play Off'},{id:15, url:'/Regions/22/Tournaments/15/Belgium-Cup', name:'Cup'},{id:459, url:'/Regions/22/Tournaments/459/Belgium-3-Division', name:'3. Division'}]},
{type:0, id:24, flg:'flg-bj', name: 'Benin', tournaments: [{id:338, url:'/Regions/24/Tournaments/338/Benin-Championnat-National', name:'Championnat National'}]},
{type:0, id:25, flg:'flg-bm', name: 'Bermuda', tournaments: [{id:372, url:'/Regions/25/Tournaments/372/Bermuda-Premier-Division', name:'Premier Division'}]},
{type:0, id:27, flg:'flg-bo', name: 'Bolivia', tournaments: [{id:255, url:'/Regions/27/Tournaments/255/Bolivia-Liga-de-Ftbol-Profesional', name:'Liga de Fútbol Profesional'},{id:528, url:'/Regions/27/Tournaments/528/Bolivia-', name:''}]},
{type:0, id:28, flg:'flg-ba', name: 'Bosnia and Herzegovina', tournaments: [{id:174, url:'/Regions/28/Tournaments/174/Bosnia-and-Herzegovina-Premier-League', name:'Premier League'},{id:404, url:'/Regions/28/Tournaments/404/Bosnia-and-Herzegovina-1-Division', name:'1. Division'}]},
{type:0, id:29, flg:'flg-bw', name: 'Botswana', tournaments: [{id:339, url:'/Regions/29/Tournaments/339/Botswana-Premier-League', name:'Premier League'}]},
{type:0, id:31, flg:'flg-br', name: 'Brazil', tournaments: [{id:95, url:'/Regions/31/Tournaments/95/Brazil-Brasileiro', name:'Brasileirão'},{id:269, url:'/Regions/31/Tournaments/269/Brazil-Serie-B', name:'Serie B'},{id:321, url:'/Regions/31/Tournaments/321/Brazil-Serie-C', name:'Serie C'},{id:330, url:'/Regions/31/Tournaments/330/Brazil-Paulista-A1', name:'Paulista A1'},{id:383, url:'/Regions/31/Tournaments/383/Brazil-Cup', name:'Cup'},{id:115, url:'/Regions/31/Tournaments/115/Brazil-Copa-dos-Campeones', name:'Copa dos Campeones'},{id:570, url:'/Regions/31/Tournaments/570/Brazil-', name:''},{id:564, url:'/Regions/31/Tournaments/564/Brazil-', name:''}]},
{type:0, id:34, flg:'flg-bg', name: 'Bulgaria', tournaments: [{id:119, url:'/Regions/34/Tournaments/119/Bulgaria-A-PFG', name:'A PFG'},{id:398, url:'/Regions/34/Tournaments/398/Bulgaria-B-PFG', name:'B PFG'},{id:143, url:'/Regions/34/Tournaments/143/Bulgaria-Cup', name:'Cup'},{id:169, url:'/Regions/34/Tournaments/169/Bulgaria-Super-Cup', name:'Super Cup'},{id:535, url:'/Regions/34/Tournaments/535/Bulgaria-', name:''}]},
{type:0, id:35, flg:'flg-bf', name: 'Burkina Faso', tournaments: [{id:340, url:'/Regions/35/Tournaments/340/Burkina-Faso-Championnat-National', name:'Championnat National'}]},
{type:0, id:38, flg:'flg-cm', name: 'Cameroon', tournaments: [{id:247, url:'/Regions/38/Tournaments/247/Cameroon-1-Division', name:'1. Division'}]},
{type:0, id:39, flg:'flg-ca', name: 'Canada', tournaments: [{id:363, url:'/Regions/39/Tournaments/363/Canada-CSL', name:'CSL'}]},
{type:0, id:40, flg:'flg-cv', name: 'Cape Verde', tournaments: [{id:342, url:'/Regions/40/Tournaments/342/Cape-Verde-Campeonato-Nacional', name:'Campeonato Nacional'}]},
{type:0, id:43, flg:'flg-td', name: 'Chad', tournaments: [{id:343, url:'/Regions/43/Tournaments/343/Chad-Premiere-Division', name:'Premiere Division'}]},
{type:0, id:44, flg:'flg-cl', name: 'Chile', tournaments: [{id:147, url:'/Regions/44/Tournaments/147/Chile-Clausura', name:'Clausura'},{id:395, url:'/Regions/44/Tournaments/395/Chile-Cup', name:'Cup'},{id:554, url:'/Regions/44/Tournaments/554/Chile-', name:''}]},
{type:0, id:45, flg:'flg-cn', name: 'China', tournaments: [{id:162, url:'/Regions/45/Tournaments/162/China-Super-league', name:'Super league'}]},
{type:0, id:48, flg:'flg-co', name: 'Colombia', tournaments: [{id:193, url:'/Regions/48/Tournaments/193/Colombia-Mustang-Cup', name:'Mustang Cup'},{id:492, url:'/Regions/48/Tournaments/492/Colombia-', name:''}]},
{type:0, id:50, flg:'flg-cg', name: 'Congo', tournaments: [{id:344, url:'/Regions/50/Tournaments/344/Congo-Linafoot', name:'Linafoot'}]},
{type:0, id:53, flg:'flg-cr', name: 'Costa Rica', tournaments: [{id:238, url:'/Regions/53/Tournaments/238/Costa-Rica-Primera-Division', name:'Primera Division'},{id:425, url:'/Regions/53/Tournaments/425/Costa-Rica-Liga-de-Ascenso', name:'Liga de Ascenso'}]},
{type:0, id:55, flg:'flg-hr', name: 'Croatia', tournaments: [{id:82, url:'/Regions/55/Tournaments/82/Croatia-Prva-HNL', name:'Prva HNL'},{id:401, url:'/Regions/55/Tournaments/401/Croatia-2-Division', name:'2. Division'},{id:109, url:'/Regions/55/Tournaments/109/Croatia-Cup', name:'Cup'},{id:133, url:'/Regions/55/Tournaments/133/Croatia-Super-Cup', name:'Super Cup'}]},
{type:0, id:56, flg:'flg-cu', name: 'Cuba', tournaments: [{id:367, url:'/Regions/56/Tournaments/367/Cuba-Campeonato-Nacional', name:'Campeonato Nacional'}]},
{type:0, id:57, flg:'flg-cy', name: 'Cyprus', tournaments: [{id:185, url:'/Regions/57/Tournaments/185/Cyprus-First-Division', name:'First Division'},{id:402, url:'/Regions/57/Tournaments/402/Cyprus-2-Division', name:'2. Division'},{id:236, url:'/Regions/57/Tournaments/236/Cyprus-Cup', name:'Cup'},{id:283, url:'/Regions/57/Tournaments/283/Cyprus-Super-Cup', name:'Super Cup'}]},
{type:0, id:58, flg:'flg-cz', name: 'Czech Republic', tournaments: [{id:78, url:'/Regions/58/Tournaments/78/Czech-Republic-Gambrinus-League', name:'Gambrinus League'},{id:234, url:'/Regions/58/Tournaments/234/Czech-Republic-Druha-League', name:'Druha League'},{id:84, url:'/Regions/58/Tournaments/84/Czech-Republic-Cup', name:'Cup'},{id:551, url:'/Regions/58/Tournaments/551/Czech-Republic-', name:''},{id:552, url:'/Regions/58/Tournaments/552/Czech-Republic-', name:''},{id:455, url:'/Regions/58/Tournaments/455/Czech-Republic-Super-Cup', name:'Super Cup'}]},
{type:0, id:59, flg:'flg-dk', name: 'Denmark', tournaments: [{id:1, url:'/Regions/59/Tournaments/1/Denmark-Superliga', name:'Superliga'},{id:34, url:'/Regions/59/Tournaments/34/Denmark-Viasat-Sport-Divisionen', name:'Viasat Sport Divisionen'},{id:35, url:'/Regions/59/Tournaments/35/Denmark-2-Division', name:'2. Division'},{id:59, url:'/Regions/59/Tournaments/59/Denmark-Ligaen', name:'Ligaen'},{id:39, url:'/Regions/59/Tournaments/39/Denmark-Cup', name:'Cup'},{id:557, url:'/Regions/59/Tournaments/557/Denmark-', name:''},{id:456, url:'/Regions/59/Tournaments/456/Denmark-Reserve-League', name:'Reserve League'}]},
{type:0, id:63, flg:'flg-ec', name: 'Ecuador', tournaments: [{id:192, url:'/Regions/63/Tournaments/192/Ecuador-Serie-A', name:'Serie A'}]},
{type:0, id:64, flg:'flg-eg', name: 'Egypt', tournaments: [{id:277, url:'/Regions/64/Tournaments/277/Egypt-Premier-League', name:'Premier League'},{id:519, url:'/Regions/64/Tournaments/519/Egypt-', name:''}]},
{type:0, id:65, flg:'flg-sv', name: 'El Salvador', tournaments: [{id:250, url:'/Regions/65/Tournaments/250/El-Salvador-Primera-Division', name:'Primera Division'}]},
{type:0, id:252, flg:'flg-gb-eng', name: 'England', tournaments: [{id:2, url:'/Regions/252/Tournaments/2/England-Premier-League', name:'Premier League'},{id:26, url:'/Regions/252/Tournaments/26/England-FA-Cup', name:'FA Cup'},{id:29, url:'/Regions/252/Tournaments/29/England-League-Cup', name:'League Cup'},{id:96, url:'/Regions/252/Tournaments/96/England-Community-Shield', name:'Community Shield'},{id:7, url:'/Regions/252/Tournaments/7/England-Championship', name:'Championship'},{id:8, url:'/Regions/252/Tournaments/8/England-League-1', name:'League 1'},{id:9, url:'/Regions/252/Tournaments/9/England-League-2', name:'League 2'},{id:70, url:'/Regions/252/Tournaments/70/England-Blue-Square-Premier', name:'Blue Square Premier'},{id:314, url:'/Regions/252/Tournaments/314/England-Blue-Square-North', name:'Blue Square North'},{id:315, url:'/Regions/252/Tournaments/315/England-Unibond-League', name:'Unibond League'},{id:23, url:'/Regions/252/Tournaments/23/England-Johnstones-Paint-Trophy', name:'Johnstones Paint Trophy'},{id:389, url:'/Regions/252/Tournaments/389/England-Premier-Reserve-League', name:'Premier Reserve League'},{id:479, url:'/Regions/252/Tournaments/479/England-', name:''},{id:497, url:'/Regions/252/Tournaments/497/England-', name:''},{id:469, url:'/Regions/252/Tournaments/469/England-WSL', name:'WSL'}]},
{type:0, id:68, flg:'flg-ee', name: 'Estonia', tournaments: [{id:148, url:'/Regions/68/Tournaments/148/Estonia-Meistriliiga', name:'Meistriliiga'},{id:405, url:'/Regions/68/Tournaments/405/Estonia-Esiliiga', name:'Esiliiga'},{id:385, url:'/Regions/68/Tournaments/385/Estonia-Super-Cup', name:'Super Cup'}]},
{type:1, id:250, flg:'flg-ceu', name: 'Europe', tournaments: [{id:62, url:'/Regions/250/Tournaments/62/Europe-UEFA-Super-Cup', name:'UEFA Super Cup'},{id:12, url:'/Regions/250/Tournaments/12/Europe-UEFA-Champions-League', name:'UEFA Champions League'},{id:30, url:'/Regions/250/Tournaments/30/Europe-UEFA-Europa-League', name:'UEFA Europa League'},{id:539, url:'/Regions/250/Tournaments/539/Europe-', name:''},{id:540, url:'/Regions/250/Tournaments/540/Europe-', name:''},{id:533, url:'/Regions/250/Tournaments/533/Europe-', name:''},{id:537, url:'/Regions/250/Tournaments/537/Europe-', name:''}]},
{type:0, id:71, flg:'flg-fo', name: 'Faroe Islands', tournaments: [{id:160, url:'/Regions/71/Tournaments/160/Faroe-Islands-Formuladeildin', name:'Formuladeildin'}]},
{type:0, id:72, flg:'flg-fj', name: 'Fiji', tournaments: [{id:346, url:'/Regions/72/Tournaments/346/Fiji-National-League', name:'National League'}]},
{type:0, id:73, flg:'flg-fi', name: 'Finland', tournaments: [{id:43, url:'/Regions/73/Tournaments/43/Finland-Veikkausliiga', name:'Veikkausliiga'},{id:202, url:'/Regions/73/Tournaments/202/Finland-Ykkonen', name:'Ykkonen'},{id:319, url:'/Regions/73/Tournaments/319/Finland-Kakkonen', name:'Kakkonen'},{id:100, url:'/Regions/73/Tournaments/100/Finland-Playoff', name:'Playoff'},{id:243, url:'/Regions/73/Tournaments/243/Finland-League-Cup', name:'League Cup'},{id:51, url:'/Regions/73/Tournaments/51/Finland-Cup', name:'Cup'}]},
{type:0, id:74, flg:'flg-fr', name: 'France', tournaments: [{id:38, url:'/Regions/74/Tournaments/38/France-Coupe-de-la-Ligue', name:'Coupe de la Ligue'},{id:22, url:'/Regions/74/Tournaments/22/France-Ligue-1', name:'Ligue 1'},{id:16, url:'/Regions/74/Tournaments/16/France-Coupe-de-France', name:'Coupe de France'},{id:54, url:'/Regions/74/Tournaments/54/France-Champions-Trophy', name:'Champions Trophy'},{id:37, url:'/Regions/74/Tournaments/37/France-Ligue-2', name:'Ligue 2'},{id:320, url:'/Regions/74/Tournaments/320/France-National', name:'National'},{id:460, url:'/Regions/74/Tournaments/460/France-CFA-Grp', name:'CFA Grp.'}]},
{type:0, id:78, flg:'flg-ga', name: 'Gabon', tournaments: [{id:345, url:'/Regions/78/Tournaments/345/Gabon-Championnat-National-de-D1', name:'Championnat National de D1'}]},
{type:0, id:79, flg:'flg-gm', name: 'Gambia', tournaments: [{id:347, url:'/Regions/79/Tournaments/347/Gambia-GFA-Premier-League', name:'GFA Premier League'}]},
{type:0, id:80, flg:'flg-ge', name: 'Georgia', tournaments: [{id:168, url:'/Regions/80/Tournaments/168/Georgia-Umaglesi-Liga', name:'Umaglesi Liga'},{id:522, url:'/Regions/80/Tournaments/522/Georgia-', name:''},{id:507, url:'/Regions/80/Tournaments/507/Georgia-Umaglesi-Liga', name:'Umaglesi Liga'}]},
{type:0, id:81, flg:'flg-de', name: 'Germany', tournaments: [{id:3, url:'/Regions/81/Tournaments/3/Germany-Bundesliga', name:'Bundesliga'},{id:24, url:'/Regions/81/Tournaments/24/Germany-DFB-Pokal', name:'DFB Pokal'},{id:307, url:'/Regions/81/Tournaments/307/Germany-Super-Cup', name:'Super Cup'},{id:6, url:'/Regions/81/Tournaments/6/Germany-Bundesliga-II', name:'Bundesliga II'},{id:308, url:'/Regions/81/Tournaments/308/Germany-Bundesliga-III', name:'Bundesliga III'},{id:56, url:'/Regions/81/Tournaments/56/Germany-Liga-Pokal', name:'Liga Pokal'},{id:274, url:'/Regions/81/Tournaments/274/Germany-Oberliga', name:'Oberliga'},{id:388, url:'/Regions/81/Tournaments/388/Germany-Promotion-Relegation', name:'Promotion/Relegation'},{id:442, url:'/Regions/81/Tournaments/442/Germany-Oberliga-Hamburg', name:'Oberliga Hamburg'}]},
{type:0, id:82, flg:'flg-gh', name: 'Ghana', tournaments: [{id:305, url:'/Regions/82/Tournaments/305/Ghana-Premier-League', name:'Premier League'}]},
{type:0, id:84, flg:'flg-gr', name: 'Greece', tournaments: [{id:65, url:'/Regions/84/Tournaments/65/Greece-Super-League', name:'Super League'},{id:69, url:'/Regions/84/Tournaments/69/Greece-Cup', name:'Cup'},{id:300, url:'/Regions/84/Tournaments/300/Greece-Super-Cup', name:'Super Cup'},{id:292, url:'/Regions/84/Tournaments/292/Greece-Second-Division', name:'Second Division'},{id:325, url:'/Regions/84/Tournaments/325/Greece-C-Ethniki-North', name:'C Ethniki North'},{id:536, url:'/Regions/84/Tournaments/536/Greece-', name:''}]},
{type:0, id:87, flg:'flg-gp', name: 'Guadeloupe', tournaments: [{id:379, url:'/Regions/87/Tournaments/379/Guadeloupe-1-Division', name:'1. Division'}]},
{type:0, id:89, flg:'flg-gt', name: 'Guatemala', tournaments: [{id:421, url:'/Regions/89/Tournaments/421/Guatemala-Primera-Division', name:'Primera Division'},{id:239, url:'/Regions/89/Tournaments/239/Guatemala-Liga-Nacional', name:'Liga Nacional'}]},
{type:0, id:91, flg:'flg-gn', name: 'Guinea', tournaments: [{id:354, url:'/Regions/91/Tournaments/354/Guinea-Championnat-National', name:'Championnat National'}]},
{type:0, id:94, flg:'flg-ht', name: 'Haiti', tournaments: [{id:376, url:'/Regions/94/Tournaments/376/Haiti-Premire-Division', name:'Première Division'}]},
{type:0, id:97, flg:'flg-hn', name: 'Honduras', tournaments: [{id:240, url:'/Regions/97/Tournaments/240/Honduras-Liga-Nacional', name:'Liga Nacional'}]},
{type:0, id:98, flg:'flg-hk', name: 'Hong Kong', tournaments: [{id:332, url:'/Regions/98/Tournaments/332/Hong-Kong-1-Division', name:'1. Division'}]},
{type:0, id:99, flg:'flg-hu', name: 'Hungary', tournaments: [{id:75, url:'/Regions/99/Tournaments/75/Hungary-Soproni-Liga', name:'Soproni Liga'},{id:419, url:'/Regions/99/Tournaments/419/Hungary-NB-II', name:'NB II'},{id:102, url:'/Regions/99/Tournaments/102/Hungary-Cup', name:'Cup'},{id:132, url:'/Regions/99/Tournaments/132/Hungary-Super-Cup', name:'Super Cup'},{id:538, url:'/Regions/99/Tournaments/538/Hungary-', name:''}]},
{type:0, id:100, flg:'flg-is', name: 'Iceland', tournaments: [{id:129, url:'/Regions/100/Tournaments/129/Iceland-Landsbankadeildin', name:'Landsbankadeildin'},{id:208, url:'/Regions/100/Tournaments/208/Iceland-1-Deild', name:'1. Deild'},{id:206, url:'/Regions/100/Tournaments/206/Iceland-Cup', name:'Cup'}]},
{type:0, id:101, flg:'flg-in', name: 'India', tournaments: [{id:333, url:'/Regions/101/Tournaments/333/India-I-League', name:'I League'},{id:582, url:'/Regions/101/Tournaments/582/India-', name:''}]},
{type:0, id:102, flg:'flg-id', name: 'Indonesia', tournaments: [{id:334, url:'/Regions/102/Tournaments/334/Indonesia-Super-Liga', name:'Super Liga'}]},
{type:1, id:247, flg:'flg-cint', name: 'International', tournaments: [{id:124, url:'/Regions/247/Tournaments/124/International-EURO-2012', name:'EURO 2012'},{id:27, url:'/Regions/247/Tournaments/27/International-Int-Friendly', name:'Int. Friendly'},{id:104, url:'/Regions/247/Tournaments/104/International-African-Cup-of-Nations', name:'African Cup of Nations'},{id:176, url:'/Regions/247/Tournaments/176/International-Summer-Olympics', name:'Summer Olympics'},{id:36, url:'/Regions/247/Tournaments/36/International-FIFA-World-Cup', name:'FIFA World Cup'},{id:89, url:'/Regions/247/Tournaments/89/International-Confederations-Cup', name:'Confederations Cup'},{id:201, url:'/Regions/247/Tournaments/201/International-EURO-U-17', name:'EURO U-17'},{id:94, url:'/Regions/247/Tournaments/94/International-Copa-America', name:'Copa America'},{id:144, url:'/Regions/247/Tournaments/144/International-World-Championship-U-20', name:'World Championship U-20'},{id:67, url:'/Regions/247/Tournaments/67/International-FIFA-Club-World-Cup', name:'FIFA Club World Cup'},{id:219, url:'/Regions/247/Tournaments/219/International-World-Championship-U-17', name:'World Championship U-17'},{id:203, url:'/Regions/247/Tournaments/203/International-Toulon-Tournament', name:'Toulon Tournament'},{id:209, url:'/Regions/247/Tournaments/209/International-Peace-Cup', name:'Peace Cup'},{id:177, url:'/Regions/247/Tournaments/177/International-Summer-Olympics-Qualifiers', name:'Summer Olympics Qualifiers'},{id:167, url:'/Regions/247/Tournaments/167/International-Champions-World-Series', name:'Champions World Series'},{id:57, url:'/Regions/247/Tournaments/57/International-Club-Friendlies', name:'Club Friendlies'},{id:166, url:'/Regions/247/Tournaments/166/International-Asian-Cup', name:'Asian Cup'},{id:123, url:'/Regions/247/Tournaments/123/International-EURO-U-21', name:'EURO U-21'},{id:244, url:'/Regions/247/Tournaments/244/International-Friendly-U-21', name:'Friendly U-21'},{id:165, url:'/Regions/247/Tournaments/165/International-EURO-U-19', name:'EURO U-19'},{id:555, url:'/Regions/247/Tournaments/555/International-', name:''},{id:546, url:'/Regions/247/Tournaments/546/International-', name:''},{id:569, url:'/Regions/247/Tournaments/569/International-', name:''},{id:563, url:'/Regions/247/Tournaments/563/International-', name:''},{id:578, url:'/Regions/247/Tournaments/578/International-', name:''},{id:499, url:'/Regions/247/Tournaments/499/International-Kagame-Inter-Club-Cup', name:'Kagame Inter-Club Cup'},{id:502, url:'/Regions/247/Tournaments/502/International-League-for-Various-Mixed-Matches', name:'League for Various/Mixed Matches'}]},
{type:0, id:103, flg:'flg-ir', name: 'Iran', tournaments: [{id:279, url:'/Regions/103/Tournaments/279/Iran-Premier-League', name:'Premier League'},{id:534, url:'/Regions/103/Tournaments/534/Iran-', name:''},{id:556, url:'/Regions/103/Tournaments/556/Iran-', name:''}]},
{type:0, id:104, flg:'flg-iq', name: 'Iraq', tournaments: [{id:384, url:'/Regions/104/Tournaments/384/Iraq-Super-League', name:'Super League'}]},
{type:0, id:105, flg:'flg-ie', name: 'Ireland', tournaments: [{id:113, url:'/Regions/105/Tournaments/113/Ireland-Airtricity-League', name:'Airtricity League'},{id:197, url:'/Regions/105/Tournaments/197/Ireland-Second-Division', name:'Second Division'},{id:116, url:'/Regions/105/Tournaments/116/Ireland-FAI-Cup', name:'FAI Cup'},{id:220, url:'/Regions/105/Tournaments/220/Ireland-Playoff', name:'Playoff'},{id:141, url:'/Regions/105/Tournaments/141/Ireland-League-Cup', name:'League Cup'},{id:566, url:'/Regions/105/Tournaments/566/Ireland-', name:''},{id:506, url:'/Regions/105/Tournaments/506/Ireland-Setanta-Sports-Cup', name:'Setanta Sports Cup'}]},
{type:0, id:107, flg:'flg-il', name: 'Israel', tournaments: [{id:97, url:'/Regions/107/Tournaments/97/Israel-Ligat-haAl', name:'Ligat ha\'Al'},{id:181, url:'/Regions/107/Tournaments/181/Israel-Liga-Leumit', name:'Liga Leumit'},{id:400, url:'/Regions/107/Tournaments/400/Israel-Toto-Cup-Ligat-Al', name:'Toto Cup Ligat Al'},{id:447, url:'/Regions/107/Tournaments/447/Israel-Ligat-Al-playoff-Qualification', name:'Ligat-Al playoff Qualification'}]},
{type:0, id:108, flg:'flg-it', name: 'Italy', tournaments: [{id:5, url:'/Regions/108/Tournaments/5/Italy-Serie-A', name:'Serie A'},{id:60, url:'/Regions/108/Tournaments/60/Italy-Coppa-Italia', name:'Coppa Italia'},{id:64, url:'/Regions/108/Tournaments/64/Italy-Supercoppa-Italiana', name:'Supercoppa Italiana'},{id:19, url:'/Regions/108/Tournaments/19/Italy-Serie-B', name:'Serie B'},{id:106, url:'/Regions/108/Tournaments/106/Italy-Serie-C', name:'Serie C'},{id:435, url:'/Regions/108/Tournaments/435/Italy-Serie-C2', name:'Serie C2'},{id:91, url:'/Regions/108/Tournaments/91/Italy-Playoff', name:'Playoff'}]},
{type:0, id:255, flg:'flg-ci', name: 'Ivory Coast', tournaments: [{id:249, url:'/Regions/255/Tournaments/249/Ivory-Coast-Ligue-1', name:'Ligue 1'}]},
{type:0, id:109, flg:'flg-jm', name: 'Jamaica', tournaments: [{id:366, url:'/Regions/109/Tournaments/366/Jamaica-Premier-League', name:'Premier League'}]},
{type:0, id:110, flg:'flg-jp', name: 'Japan', tournaments: [{id:150, url:'/Regions/110/Tournaments/150/Japan-J-League', name:'J- League'},{id:324, url:'/Regions/110/Tournaments/324/Japan-J-League-2', name:'J. League 2'},{id:186, url:'/Regions/110/Tournaments/186/Japan-Cup', name:'Cup'},{id:358, url:'/Regions/110/Tournaments/358/Japan-Cup', name:'Cup'},{id:248, url:'/Regions/110/Tournaments/248/Japan-Super-Cup', name:'Super Cup'},{id:559, url:'/Regions/110/Tournaments/559/Japan-', name:''}]},
{type:0, id:112, flg:'flg-jo', name: 'Jordan', tournaments: [{id:284, url:'/Regions/112/Tournaments/284/Jordan-1-Division', name:'1. Division'}]},
{type:0, id:113, flg:'flg-kz', name: 'Kazakhstan', tournaments: [{id:153, url:'/Regions/113/Tournaments/153/Kazakhstan-Superliga', name:'Superliga'},{id:558, url:'/Regions/113/Tournaments/558/Kazakhstan-', name:''}]},
{type:0, id:114, flg:'flg-ke', name: 'Kenya', tournaments: [{id:355, url:'/Regions/114/Tournaments/355/Kenya-Premier-League', name:'Premier League'},{id:561, url:'/Regions/114/Tournaments/561/Kenya-', name:''},{id:531, url:'/Regions/114/Tournaments/531/Kenya-', name:''},{id:500, url:'/Regions/114/Tournaments/500/Kenya-', name:''},{id:495, url:'/Regions/114/Tournaments/495/Kenya-FKL-Nationwide-One', name:'FKL Nationwide One'},{id:496, url:'/Regions/114/Tournaments/496/Kenya-Kenya-Cup', name:'Kenya Cup'}]},
{type:0, id:118, flg:'flg-kw', name: 'Kuwait', tournaments: [{id:293, url:'/Regions/118/Tournaments/293/Kuwait-1-Division', name:'1. Division'}]},
{type:0, id:121, flg:'flg-lv', name: 'Latvia', tournaments: [{id:155, url:'/Regions/121/Tournaments/155/Latvia-Virsliga', name:'Virsliga'}]},
{type:0, id:122, flg:'flg-lb', name: 'Lebanon', tournaments: [{id:298, url:'/Regions/122/Tournaments/298/Lebanon-1-Division', name:'1. Division'}]},
{type:0, id:123, flg:'flg-ls', name: 'Lesotho', tournaments: [{id:356, url:'/Regions/123/Tournaments/356/Lesotho-Buddie-Premier-League', name:'Buddie Premier League'}]},
{type:0, id:124, flg:'flg-lr', name: 'Liberia', tournaments: [{id:351, url:'/Regions/124/Tournaments/351/Liberia-1-Divsion', name:'1. Divsion'}]},
{type:0, id:125, flg:'flg-ly', name: 'Libya', tournaments: [{id:288, url:'/Regions/125/Tournaments/288/Libya-1-Division', name:'1. Division'}]},
{type:0, id:127, flg:'flg-lt', name: 'Lithuania', tournaments: [{id:159, url:'/Regions/127/Tournaments/159/Lithuania-A-Lyga', name:'A Lyga'}]},
{type:0, id:128, flg:'flg-lu', name: 'Luxembourg', tournaments: [{id:172, url:'/Regions/128/Tournaments/172/Luxembourg-1-Division', name:'1. Division'},{id:407, url:'/Regions/128/Tournaments/407/Luxembourg-2-Division', name:'2. Division'},{id:452, url:'/Regions/128/Tournaments/452/Luxembourg-1-Division-Qualification', name:'1. Division Qualification'}]},
{type:0, id:130, flg:'flg-mk', name: 'Macedonia', tournaments: [{id:396, url:'/Regions/130/Tournaments/396/Macedonia-Vtora-Liga', name:'Vtora Liga'},{id:453, url:'/Regions/130/Tournaments/453/Macedonia-', name:''}]},
{type:0, id:132, flg:'flg-mw', name: 'Malawi', tournaments: [{id:350, url:'/Regions/132/Tournaments/350/Malawi-Super-League', name:'Super League'}]},
{type:0, id:133, flg:'flg-my', name: 'Malaysia', tournaments: [{id:336, url:'/Regions/133/Tournaments/336/Malaysia-Super-Liga', name:'Super Liga'}]},
{type:0, id:135, flg:'flg-ml', name: 'Mali', tournaments: [{id:352, url:'/Regions/135/Tournaments/352/Mali-Championnat-National', name:'Championnat National'}]},
{type:0, id:136, flg:'flg-mt', name: 'Malta', tournaments: [{id:184, url:'/Regions/136/Tournaments/184/Malta-Premier-League', name:'Premier League'},{id:410, url:'/Regions/136/Tournaments/410/Malta-1-Division', name:'1. Division'}]},
{type:0, id:138, flg:'flg-mq', name: 'Martinique', tournaments: [{id:353, url:'/Regions/138/Tournaments/353/Martinique-Division-dHonneur', name:'Division d´Honneur'}]},
{type:0, id:140, flg:'flg-mu', name: 'Mauritius', tournaments: [{id:357, url:'/Regions/140/Tournaments/357/Mauritius-Barclays-League', name:'Barclays League'}]},
{type:0, id:142, flg:'flg-mx', name: 'Mexico', tournaments: [{id:103, url:'/Regions/142/Tournaments/103/Mexico-Primera-Division', name:'Primera Division'},{id:326, url:'/Regions/142/Tournaments/326/Mexico-Primera-A', name:'Primera A'},{id:532, url:'/Regions/142/Tournaments/532/Mexico-', name:''},{id:547, url:'/Regions/142/Tournaments/547/Mexico-', name:''},{id:572, url:'/Regions/142/Tournaments/572/Mexico-', name:''}]},
{type:0, id:144, flg:'flg-md', name: 'Moldova', tournaments: [{id:178, url:'/Regions/144/Tournaments/178/Moldova-Divizia-Nationala', name:'Divizia Nationala'},{id:411, url:'/Regions/144/Tournaments/411/Moldova-2-Division', name:'2. Division'}]},
{type:0, id:147, flg:'flg-me', name: 'Montenegro', tournaments: [{id:235, url:'/Regions/147/Tournaments/235/Montenegro-1-Division', name:'1. Division'},{id:412, url:'/Regions/147/Tournaments/412/Montenegro-2-Division', name:'2. Division'},{id:454, url:'/Regions/147/Tournaments/454/Montenegro-1-Division-Playoff', name:'1. Division Playoff'}]},
{type:0, id:149, flg:'flg-ma', name: 'Morocco', tournaments: [{id:291, url:'/Regions/149/Tournaments/291/Morocco-GNF-1', name:'GNF 1'},{id:523, url:'/Regions/149/Tournaments/523/Morocco-', name:''}]},
{type:0, id:150, flg:'flg-mz', name: 'Mozambique', tournaments: [{id:377, url:'/Regions/150/Tournaments/377/Mozambique-Mocambola', name:'Mocambola'}]},
{type:0, id:152, flg:'flg-na', name: 'Namibia', tournaments: [{id:364, url:'/Regions/152/Tournaments/364/Namibia-Premier-League', name:'Premier League'}]},
{type:0, id:155, flg:'flg-nl', name: 'Netherlands', tournaments: [{id:13, url:'/Regions/155/Tournaments/13/Netherlands-Eredivisie', name:'Eredivisie'},{id:47, url:'/Regions/155/Tournaments/47/Netherlands-KNVB-Cup', name:'KNVB Cup'},{id:120, url:'/Regions/155/Tournaments/120/Netherlands-Super-Cup', name:'Super Cup'},{id:66, url:'/Regions/155/Tournaments/66/Netherlands-Jupiler-League', name:'Jupiler League'},{id:88, url:'/Regions/155/Tournaments/88/Netherlands-Playoff', name:'Playoff'},{id:457, url:'/Regions/155/Tournaments/457/Netherlands-Topklasse', name:'Topklasse'}]},
{type:0, id:158, flg:'flg-nz', name: 'New Zealand', tournaments: [{id:303, url:'/Regions/158/Tournaments/303/New-Zealand-Premier-League', name:'Premier League'}]},
{type:0, id:159, flg:'flg-ni', name: 'Nicaragua', tournaments: [{id:362, url:'/Regions/159/Tournaments/362/Nicaragua-Campeonato-Nacional', name:'Campeonato Nacional'}]},
{type:0, id:161, flg:'flg-ng', name: 'Nigeria', tournaments: [{id:294, url:'/Regions/161/Tournaments/294/Nigeria-1-Division', name:'1. Division'}]},
{type:1, id:264, flg:'flg-cna', name: 'North & Central America', tournaments: [{id:222, url:'/Regions/264/Tournaments/222/North-Central-America-CONCACAF-Champions-Cup', name:'CONCACAF Champions Cup'},{id:131, url:'/Regions/264/Tournaments/131/North-Central-America-CONCACAF-Gold-Cup', name:'CONCACAF Gold Cup'},{id:462, url:'/Regions/264/Tournaments/462/North-Central-America-', name:''},{id:543, url:'/Regions/264/Tournaments/543/North-Central-America-', name:''}]},
{type:0, id:258, flg:'flg-gb-nir', name: 'Northern Ireland', tournaments: [{id:126, url:'/Regions/258/Tournaments/126/Northern-Ireland-Premiership', name:'Premiership'},{id:329, url:'/Regions/258/Tournaments/329/Northern-Ireland-Promotion-Relegation', name:'Promotion/Relegation'},{id:328, url:'/Regions/258/Tournaments/328/Northern-Ireland-Cup', name:'Cup'},{id:545, url:'/Regions/258/Tournaments/545/Northern-Ireland-', name:''},{id:446, url:'/Regions/258/Tournaments/446/Northern-Ireland-1-Division', name:'1. Division'}]},
{type:0, id:165, flg:'flg-no', name: 'Norway', tournaments: [{id:41, url:'/Regions/165/Tournaments/41/Norway-Tippeligaen', name:'Tippeligaen'},{id:50, url:'/Regions/165/Tournaments/50/Norway-1-Division', name:'1. Division'},{id:200, url:'/Regions/165/Tournaments/200/Norway-2-Division', name:'2. Division'},{id:99, url:'/Regions/165/Tournaments/99/Norway-Playoff', name:'Playoff'},{id:52, url:'/Regions/165/Tournaments/52/Norway-Cup', name:'Cup'},{id:205, url:'/Regions/165/Tournaments/205/Norway-Cup', name:'Cup'},{id:386, url:'/Regions/165/Tournaments/386/Norway-Super-Cup', name:'Super Cup'},{id:542, url:'/Regions/165/Tournaments/542/Norway-', name:''}]},
{type:0, id:166, flg:'flg-om', name: 'Oman', tournaments: [{id:304, url:'/Regions/166/Tournaments/304/Oman-1-Division', name:'1. Division'}]},
{type:0, id:169, flg:'flg-ps', name: 'Palestine', tournaments: [{id:464, url:'/Regions/169/Tournaments/464/Palestine-Division-A', name:'Division A'}]},
{type:0, id:170, flg:'flg-pa', name: 'Panama', tournaments: [{id:368, url:'/Regions/170/Tournaments/368/Panama-ANAPROF', name:'ANAPROF'}]},
{type:0, id:172, flg:'flg-py', name: 'Paraguay', tournaments: [{id:246, url:'/Regions/172/Tournaments/246/Paraguay-Primera-Division', name:'Primera Division'},{id:422, url:'/Regions/172/Tournaments/422/Paraguay-Division-Intermedia', name:'Division Intermedia'}]},
{type:0, id:173, flg:'flg-pe', name: 'Peru', tournaments: [{id:195, url:'/Regions/173/Tournaments/195/Peru-Primera-Division', name:'Primera Division'}]},
{type:0, id:176, flg:'flg-pl', name: 'Poland', tournaments: [{id:76, url:'/Regions/176/Tournaments/76/Poland-Ekstraklasa', name:'Ekstraklasa'},{id:232, url:'/Regions/176/Tournaments/232/Poland-1-Division', name:'1. Division'},{id:311, url:'/Regions/176/Tournaments/311/Poland-2-Division', name:'2. Division'},{id:204, url:'/Regions/176/Tournaments/204/Poland-Playoff', name:'Playoff'},{id:101, url:'/Regions/176/Tournaments/101/Poland-Cup', name:'Cup'},{id:110, url:'/Regions/176/Tournaments/110/Poland-League-Cup', name:'League Cup'},{id:231, url:'/Regions/176/Tournaments/231/Poland-Super-Cup', name:'Super Cup'}]},
{type:0, id:177, flg:'flg-pt', name: 'Portugal', tournaments: [{id:21, url:'/Regions/177/Tournaments/21/Portugal-Liga-Sagres', name:'Liga Sagres'},{id:11, url:'/Regions/177/Tournaments/11/Portugal-Taa-de-Portugal', name:'Taça de Portugal'},{id:122, url:'/Regions/177/Tournaments/122/Portugal-Super-Cup', name:'Super Cup'},{id:414, url:'/Regions/177/Tournaments/414/Portugal-2-Division', name:'2. Division'},{id:139, url:'/Regions/177/Tournaments/139/Portugal-Liga-Vitalis', name:'Liga Vitalis'},{id:275, url:'/Regions/177/Tournaments/275/Portugal-Carlsberg-Cup', name:'Carlsberg Cup'}]},
{type:0, id:178, flg:'flg-pr', name: 'Puerto Rico', tournaments: [{id:380, url:'/Regions/178/Tournaments/380/Puerto-Rico-Premier-League', name:'Premier League'}]},
{type:0, id:179, flg:'flg-qa', name: 'Qatar', tournaments: [{id:285, url:'/Regions/179/Tournaments/285/Qatar-1-Division', name:'1. Division'}]},
{type:0, id:181, flg:'flg-ro', name: 'Romania', tournaments: [{id:121, url:'/Regions/181/Tournaments/121/Romania-Liga-I', name:'Liga I'},{id:415, url:'/Regions/181/Tournaments/415/Romania-Liga-II', name:'Liga II'},{id:145, url:'/Regions/181/Tournaments/145/Romania-Cup', name:'Cup'},{id:213, url:'/Regions/181/Tournaments/213/Romania-Super-Cup', name:'Super Cup'},{id:571, url:'/Regions/181/Tournaments/571/Romania-', name:''}]},
{type:0, id:182, flg:'flg-ru', name: 'Russia', tournaments: [{id:77, url:'/Regions/182/Tournaments/77/Russia-Premier-League', name:'Premier League'},{id:111, url:'/Regions/182/Tournaments/111/Russia-Cup', name:'Cup'},{id:127, url:'/Regions/182/Tournaments/127/Russia-Super-Cup', name:'Super Cup'},{id:257, url:'/Regions/182/Tournaments/257/Russia-1-Division', name:'1. Division'},{id:544, url:'/Regions/182/Tournaments/544/Russia-', name:''},{id:527, url:'/Regions/182/Tournaments/527/Russia-', name:''}]},
{type:0, id:183, flg:'flg-rw', name: 'Rwanda', tournaments: [{id:369, url:'/Regions/183/Tournaments/369/Rwanda-Championnat-National', name:'Championnat National'}]},
{type:0, id:186, flg:'flg-kn', name: 'Saint Kitts and Nevis', tournaments: [{id:374, url:'/Regions/186/Tournaments/374/Saint-Kitts-and-Nevis-SKNFA-League', name:'SKNFA League'}]},
{type:0, id:190, flg:'flg-vc', name: 'Saint Vincent and the Grenadines', tournaments: [{id:493, url:'/Regions/190/Tournaments/493/Saint-Vincent-and-the-Grenadines-', name:''}]},
{type:0, id:192, flg:'flg-sm', name: 'San Marino', tournaments: [{id:331, url:'/Regions/192/Tournaments/331/San-Marino-Campionato', name:'Campionato'}]},
{type:0, id:194, flg:'flg-sa', name: 'Saudi Arabia', tournaments: [{id:282, url:'/Regions/194/Tournaments/282/Saudi-Arabia-1-Division', name:'1. Division'}]},
{type:0, id:253, flg:'flg-gb-sct', name: 'Scotland', tournaments: [{id:20, url:'/Regions/253/Tournaments/20/Scotland-Premier-League', name:'Premier League'},{id:10, url:'/Regions/253/Tournaments/10/Scotland-Tennents-Scottish-Cup', name:'Tennents Scottish Cup'},{id:71, url:'/Regions/253/Tournaments/71/Scotland-1-Division', name:'1. Division'},{id:72, url:'/Regions/253/Tournaments/72/Scotland-2-Division', name:'2. Division'},{id:73, url:'/Regions/253/Tournaments/73/Scotland-3-Division', name:'3. Division'},{id:225, url:'/Regions/253/Tournaments/225/Scotland-Playoff', name:'Playoff'},{id:25, url:'/Regions/253/Tournaments/25/Scotland-Co-operative-Insurance-Cup', name:'Co-operative Insurance Cup'},{id:118, url:'/Regions/253/Tournaments/118/Scotland-Alba-Challenge-Cup', name:'Alba Challenge Cup'}]},
{type:0, id:195, flg:'flg-sn', name: 'Senegal', tournaments: [{id:359, url:'/Regions/195/Tournaments/359/Senegal-Championnat-National', name:'Championnat National'}]},
{type:0, id:196, flg:'flg-rs', name: 'Serbia', tournaments: [{id:80, url:'/Regions/196/Tournaments/80/Serbia-Super-Liga', name:'Super Liga'},{id:416, url:'/Regions/196/Tournaments/416/Serbia-Prva-Liga', name:'Prva Liga'},{id:112, url:'/Regions/196/Tournaments/112/Serbia-Cup', name:'Cup'}]},
{type:0, id:198, flg:'flg-sl', name: 'Sierra Leone', tournaments: [{id:360, url:'/Regions/198/Tournaments/360/Sierra-Leone-Premier-League', name:'Premier League'}]},
{type:0, id:199, flg:'flg-sg', name: 'Singapore', tournaments: [{id:254, url:'/Regions/199/Tournaments/254/Singapore-SLeague', name:'S.League'},{id:443, url:'/Regions/199/Tournaments/443/Singapore-Cup', name:'Cup'},{id:444, url:'/Regions/199/Tournaments/444/Singapore-League-Cup', name:'League Cup'}]},
{type:0, id:200, flg:'flg-sk', name: 'Slovakia', tournaments: [{id:74, url:'/Regions/200/Tournaments/74/Slovakia-Corgon-Liga', name:'Corgon Liga'},{id:323, url:'/Regions/200/Tournaments/323/Slovakia-1-Division', name:'1. Division'},{id:107, url:'/Regions/200/Tournaments/107/Slovakia-FA-Cup', name:'FA Cup'},{id:130, url:'/Regions/200/Tournaments/130/Slovakia-Super-Cup', name:'Super Cup'}]},
{type:0, id:201, flg:'flg-si', name: 'Slovenia', tournaments: [{id:79, url:'/Regions/201/Tournaments/79/Slovenia-PrvaLiga', name:'PrvaLiga'},{id:417, url:'/Regions/201/Tournaments/417/Slovenia-2-Division', name:'2. Division'},{id:272, url:'/Regions/201/Tournaments/272/Slovenia-Playoff', name:'Playoff'},{id:108, url:'/Regions/201/Tournaments/108/Slovenia-Cup', name:'Cup'},{id:273, url:'/Regions/201/Tournaments/273/Slovenia-Super-Cup', name:'Super Cup'}]},
{type:0, id:202, flg:'flg-sb', name: 'Solomon Islands', tournaments: [{id:375, url:'/Regions/202/Tournaments/375/Solomon-Islands-National-Club-Championship', name:'National Club Championship'}]},
{type:0, id:204, flg:'flg-za', name: 'South Africa', tournaments: [{id:278, url:'/Regions/204/Tournaments/278/South-Africa-Premier-Soccer-League', name:'Premier Soccer League'},{id:525, url:'/Regions/204/Tournaments/525/South-Africa-', name:''},{id:580, url:'/Regions/204/Tournaments/580/South-Africa-', name:''}]},
{type:1, id:265, flg:'flg-csa', name: 'South America', tournaments: [{id:105, url:'/Regions/265/Tournaments/105/South-America-Copa-Libertadores', name:'Copa Libertadores'},{id:146, url:'/Regions/265/Tournaments/146/South-America-Copa-Sudamericana', name:'Copa Sudamericana'},{id:271, url:'/Regions/265/Tournaments/271/South-America-Recopa-Sudamericana', name:'Recopa Sudamericana'}]},
{type:0, id:260, flg:'flg-kr', name: 'South Korea', tournaments: [{id:387, url:'/Regions/260/Tournaments/387/South-Korea-K-League', name:'K. League'},{id:418, url:'/Regions/260/Tournaments/418/South-Korea-K2-League', name:'K2 League'},{id:560, url:'/Regions/260/Tournaments/560/South-Korea-', name:''}]},
{type:0, id:206, flg:'flg-es', name: 'Spain', tournaments: [{id:4, url:'/Regions/206/Tournaments/4/Spain-La-Liga', name:'La Liga'},{id:14, url:'/Regions/206/Tournaments/14/Spain-Copa-del-Rey', name:'Copa del Rey'},{id:61, url:'/Regions/206/Tournaments/61/Spain-Supercopa-de-Espana', name:'Supercopa de Espana'},{id:63, url:'/Regions/206/Tournaments/63/Spain-LIGA-Adelante', name:'LIGA Adelante'},{id:318, url:'/Regions/206/Tournaments/318/Spain-Segunda-B', name:'Segunda B'},{id:438, url:'/Regions/206/Tournaments/438/Spain-Tercera-Division', name:'Tercera Division'}]},
{type:0, id:208, flg:'flg-sd', name: 'Sudan', tournaments: [{id:316, url:'/Regions/208/Tournaments/316/Sudan-Premier-League', name:'Premier League'}]},
{type:0, id:211, flg:'flg-sz', name: 'Swaziland', tournaments: [{id:297, url:'/Regions/211/Tournaments/297/Swaziland-1-Division', name:'1. Division'}]},
{type:0, id:212, flg:'flg-se', name: 'Sweden', tournaments: [{id:40, url:'/Regions/212/Tournaments/40/Sweden-Allsvenskan', name:'Allsvenskan'},{id:48, url:'/Regions/212/Tournaments/48/Sweden-Superettan', name:'Superettan'},{id:158, url:'/Regions/212/Tournaments/158/Sweden-2-Division', name:'2. Division'},{id:98, url:'/Regions/212/Tournaments/98/Sweden-Allsvenskan-qualification', name:'Allsvenskan qualification'},{id:310, url:'/Regions/212/Tournaments/310/Sweden-Promotion-Relegation-2', name:'Promotion/Relegation 2'},{id:393, url:'/Regions/212/Tournaments/393/Sweden-Damallsvenskan', name:'Damallsvenskan'},{id:42, url:'/Regions/212/Tournaments/42/Sweden-Cup', name:'Cup'},{id:258, url:'/Regions/212/Tournaments/258/Sweden-Super-Cup', name:'Super Cup'},{id:553, url:'/Regions/212/Tournaments/553/Sweden-', name:''},{id:439, url:'/Regions/212/Tournaments/439/Sweden-1-Division', name:'1. Division'}]},
{type:0, id:213, flg:'flg-ch', name: 'Switzerland', tournaments: [{id:33, url:'/Regions/213/Tournaments/33/Switzerland-Super-League', name:'Super League'},{id:55, url:'/Regions/213/Tournaments/55/Switzerland-Challenge-League', name:'Challenge League'},{id:163, url:'/Regions/213/Tournaments/163/Switzerland-Playoff', name:'Playoff'},{id:45, url:'/Regions/213/Tournaments/45/Switzerland-Switzerland-Cup', name:'Switzerland Cup'},{id:529, url:'/Regions/213/Tournaments/529/Switzerland-', name:''},{id:461, url:'/Regions/213/Tournaments/461/Switzerland-1Liga', name:'1.Liga'}]},
{type:0, id:214, flg:'flg-sy', name: 'Syria', tournaments: [{id:296, url:'/Regions/214/Tournaments/296/Syria-1-Division', name:'1. Division'}]},
{type:0, id:215, flg:'flg-tw', name: 'Taiwan', tournaments: [{id:337, url:'/Regions/215/Tournaments/337/Taiwan-Division-A', name:'Division A'}]},
{type:0, id:217, flg:'flg-tz', name: 'Tanzania', tournaments: [{id:382, url:'/Regions/217/Tournaments/382/Tanzania-Premier-League', name:'Premier League'}]},
{type:0, id:218, flg:'flg-th', name: 'Thailand', tournaments: [{id:335, url:'/Regions/218/Tournaments/335/Thailand-Premier-League', name:'Premier League'}]},
{type:0, id:220, flg:'flg-tg', name: 'Togo', tournaments: [{id:365, url:'/Regions/220/Tournaments/365/Togo-Championnat-National', name:'Championnat National'}]},
{type:0, id:223, flg:'flg-tt', name: 'Trinidad and Tobago', tournaments: [{id:361, url:'/Regions/223/Tournaments/361/Trinidad-and-Tobago-Professional-League', name:'Professional League'}]},
{type:0, id:224, flg:'flg-tn', name: 'Tunisia', tournaments: [{id:276, url:'/Regions/224/Tournaments/276/Tunisia-Ligue-Professionnelle-1', name:'Ligue Professionnelle 1'},{id:524, url:'/Regions/224/Tournaments/524/Tunisia-', name:''}]},
{type:0, id:225, flg:'flg-tr', name: 'Turkey', tournaments: [{id:17, url:'/Regions/225/Tournaments/17/Turkey-Super-Lig', name:'Super Lig'},{id:44, url:'/Regions/225/Tournaments/44/Turkey-Cup', name:'Cup'},{id:233, url:'/Regions/225/Tournaments/233/Turkey-Super-Cup', name:'Super Cup'},{id:140, url:'/Regions/225/Tournaments/140/Turkey-TFF-Lig-A', name:'TFF Lig A'},{id:280, url:'/Regions/225/Tournaments/280/Turkey-TFF-Lig-B', name:'TFF Lig B'},{id:327, url:'/Regions/225/Tournaments/327/Turkey-3-Lig', name:'3. Lig'},{id:229, url:'/Regions/225/Tournaments/229/Turkey-Playoff', name:'Playoff'},{id:514, url:'/Regions/225/Tournaments/514/Turkey-Spor-Toto-Cup', name:'Spor Toto Cup'}]},
{type:0, id:231, flg:'flg-ae', name: 'UAE', tournaments: [{id:295, url:'/Regions/231/Tournaments/295/UAE-1-Division', name:'1. Division'}]},
{type:0, id:229, flg:'flg-ug', name: 'Uganda', tournaments: [{id:371, url:'/Regions/229/Tournaments/371/Uganda-Super-League', name:'Super League'}]},
{type:0, id:230, flg:'flg-ua', name: 'Ukraine', tournaments: [{id:114, url:'/Regions/230/Tournaments/114/Ukraine-Premier-League', name:'Premier League'},{id:125, url:'/Regions/230/Tournaments/125/Ukraine-Cup', name:'Cup'},{id:164, url:'/Regions/230/Tournaments/164/Ukraine-Super-Cup', name:'Super Cup'},{id:408, url:'/Regions/230/Tournaments/408/Ukraine-1-Division', name:'1. Division'}]},
{type:0, id:235, flg:'flg-uy', name: 'Uruguay', tournaments: [{id:196, url:'/Regions/235/Tournaments/196/Uruguay-Primera-Division', name:'Primera Division'},{id:423, url:'/Regions/235/Tournaments/423/Uruguay-Segunda-Division', name:'Segunda Division'}]},
{type:0, id:233, flg:'flg-us', name: 'USA', tournaments: [{id:85, url:'/Regions/233/Tournaments/85/USA-Major-League-Soccer', name:'Major League Soccer'},{id:434, url:'/Regions/233/Tournaments/434/USA-USA-1', name:'USA 1'},{id:322, url:'/Regions/233/Tournaments/322/USA-USL-1', name:'USL 1'},{id:568, url:'/Regions/233/Tournaments/568/USA-US-Open', name:'US Open'},{id:498, url:'/Regions/233/Tournaments/498/USA-USL-Pro-League', name:'USL Pro League'}]},
{type:0, id:236, flg:'flg-uz', name: 'Uzbekistan', tournaments: [{id:251, url:'/Regions/236/Tournaments/251/Uzbekistan-Oliy-League', name:'Oliy League'},{id:521, url:'/Regions/236/Tournaments/521/Uzbekistan-', name:''}]},
{type:0, id:238, flg:'flg-ve', name: 'Venezuela', tournaments: [{id:237, url:'/Regions/238/Tournaments/237/Venezuela-Primera-Division', name:'Primera Division'},{id:420, url:'/Regions/238/Tournaments/420/Venezuela-Segunda-Division-Apertura', name:'Segunda Division - Apertura'}]},
{type:0, id:239, flg:'flg-vn', name: 'Viet Nam', tournaments: [{id:392, url:'/Regions/239/Tournaments/392/Viet-Nam-V-league', name:'V-league'}]},
{type:0, id:254, flg:'flg-gb-wls', name: 'Wales', tournaments: [{id:138, url:'/Regions/254/Tournaments/138/Wales-Premier-Division', name:'Premier Division'},{id:151, url:'/Regions/254/Tournaments/151/Wales-Cup', name:'Cup'},{id:520, url:'/Regions/254/Tournaments/520/Wales-', name:''},{id:448, url:'/Regions/254/Tournaments/448/Wales-Welsh-Cup', name:'Welsh Cup'}]},
{type:0, id:244, flg:'flg-ye', name: 'Yemen', tournaments: [{id:306, url:'/Regions/244/Tournaments/306/Yemen-1-Division', name:'1. Division'}]},
{type:0, id:245, flg:'flg-zm', name: 'Zambia', tournaments: [{id:252, url:'/Regions/245/Tournaments/252/Zambia-1-Division', name:'1. Division'}]},
{type:0, id:246, flg:'flg-zw', name: 'Zimbabwe', tournaments: [{id:253, url:'/Regions/246/Tournaments/253/Zimbabwe-1-Division', name:'1. Division'}]}];
allRegions.forEach(function(region){
    if(!region.type){
        region.tournaments.forEach(function(tournament){
            crawler.queueURL(host + tournament.url);
        })
    }
})
crawler.start();
//http://www.whoscored.com/tournamentsfeed/9155/Fixtures/?d=2014W42&isAggregate=false