/**
 * @author nttdocomo
 */
var http = require("http"),
excute = require('../../promiseExcute'),
StringDecoder = require('string_decoder').StringDecoder,
mysql = require('mysql'),
moment = require('moment-timezone'),
migrate_match = require('./migrate_match'),
migrate_match_player_statistics = require('./migrate_match_player_statistics'),
_ = require('underscore'),
input_date = process.argv[2],
host = 'http://www.whoscored.com',
crawler = require('./matchesfeedconfig');
var date = [],
condition = 0,
now = moment.utc(),
clone = now.clone();
migrate_match().then(migrate_match_player_statistics).then(function(){
    crawler.queueURL(host + '/Matches/969706/Live')
    // crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=passing&statsAccumulationType=0&teamIds=71&matchId=100219')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=offensive&statsAccumulationType=0&isCurrent=true&teamIs=2864&matchId=982470')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=defensive&statsAccumulationType=0&isCurrent=true&teamIs=37&matchId=969703')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=passing&statsAccumulationType=0&teamIds=3429&matchId=99703')
	// crawler.queueURL(host + '/MatchesFeed/969706/MatchCentre')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=summary&subcategory=all&statsAccumulationType=0&isCurrnt=true&teamIds=38&matchId=969706')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=offensive&statsAccumulationType=0&isCurrent=true&teamIs=110&matchId=969709')
	// crawler.queueURL(host + '/MatchesFeed/969711/MatchCentre')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=summary&subcategory=all&statsAccumulationType=0&isCurrnt=true&teamIds=1147&matchId=969711')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=passing&statsAccumulationType=0&teamIds=1147&matchId=99711')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=defensive&statsAccumulationType=0&isCurrent=true&teamIs=1147&matchId=969711')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=offensive&statsAccumulationType=0&isCurrent=true&teamIs=1147&matchId=969711')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=summary&subcategory=all&statsAccumulationType=0&isCurrnt=true&teamIds=47&matchId=969711')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=passing&statsAccumulationType=0&teamIds=47&matchId=96911')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=defensive&statsAccumulationType=0&isCurrent=true&teamIs=47&matchId=969711')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=offensive&statsAccumulationType=0&isCurrent=true&teamIs=47&matchId=969711')
	// crawler.queueURL(host + '/MatchesFeed/960751/MatchCentre')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=summary&subcategory=all&statsAccumulationType=0&isCurrnt=true&teamIds=950&matchId=960751')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=passing&statsAccumulationType=0&teamIds=950&matchId=96751')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=defensive&statsAccumulationType=0&isCurrent=true&teamIs=950&matchId=960751')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=offensive&statsAccumulationType=0&isCurrent=true&teamIs=950&matchId=960751')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=summary&subcategory=all&statsAccumulationType=0&isCurrnt=true&teamIds=613&matchId=960751')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=passing&statsAccumulationType=0&teamIds=613&matchId=96751')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=defensive&statsAccumulationType=0&isCurrent=true&teamIs=613&matchId=960751')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=offensive&statsAccumulationType=0&isCurrent=true&teamIs=613&matchId=960751')
	// crawler.queueURL(host + '/MatchesFeed/985611/MatchCentre')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=summary&subcategory=all&statsAccumulationType=0&isCurrnt=true&teamIds=65&matchId=985611')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=passing&statsAccumulationType=0&teamIds=65&matchId=98511')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=defensive&statsAccumulationType=0&isCurrent=true&teamIs=65&matchId=985611')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=offensive&statsAccumulationType=0&isCurrent=true&teamIs=65&matchId=985611')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=summary&subcategory=all&statsAccumulationType=0&isCurrnt=true&teamIds=59&matchId=985611')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=passing&statsAccumulationType=0&teamIds=59&matchId=98511')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=defensive&statsAccumulationType=0&isCurrent=true&teamIs=59&matchId=985611')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=offensive&statsAccumulationType=0&isCurrent=true&teamIs=59&matchId=985611')
	// crawler.queueURL(host + '/MatchesFeed/959611/MatchCentre')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=summary&subcategory=all&statsAccumulationType=0&isCurrnt=true&teamIds=162&matchId=959611')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=passing&statsAccumulationType=0&teamIds=162&matchId=95611')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=defensive&statsAccumulationType=0&isCurrent=true&teamIs=162&matchId=959611')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=offensive&statsAccumulationType=0&isCurrent=true&teamIs=162&matchId=959611')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=summary&subcategory=all&statsAccumulationType=0&isCurrnt=true&teamIds=18&matchId=959611')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=passing&statsAccumulationType=0&teamIds=18&matchId=95911')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=defensive&statsAccumulationType=0&isCurrent=true&teamIs=18&matchId=959611')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=offensive&statsAccumulationType=0&isCurrent=true&teamIs=18&matchId=959611')
	// crawler.queueURL(host + '/MatchesFeed/959641/MatchCentre')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=summary&subcategory=all&statsAccumulationType=0&isCurrnt=true&teamIds=167&matchId=959641')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=passing&statsAccumulationType=0&teamIds=167&matchId=95641')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=defensive&statsAccumulationType=0&isCurrent=true&teamIs=167&matchId=959641')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=passing&statsAccumulationType=0&teamIds=25&matchId=95822')
	// crawler.queueURL(host + '/MatchesFeed/958929/MatchCentre')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=summary&subcategory=all&statsAccumulationType=0&isCurrnt=true&teamIds=160&matchId=958929')
	// crawler.queueURL(host + '/Players/85006')
	// crawler.queueURL(host + '/Players/68666')
	// crawler.queueURL(host + '/Players/82277')
	// crawler.queueURL(host + '/Players/231119')
	// crawler.queueURL(host + '/Players/34388')
	// crawler.queueURL(host + '/Players/106454')
	// crawler.queueURL(host + '/Players/136945')
	// crawler.queueURL(host + '/Players/295951')
	// crawler.queueURL(host + '/Players/82088')
	// crawler.queueURL(host + '/Players/8379')
	// crawler.queueURL(host + '/Players/5347')
	// crawler.queueURL(host + '/Players/276357')
	// crawler.queueURL(host + '/Players/35745')
	// crawler.queueURL(host + '/Players/104886')
	// crawler.queueURL(host + '/Players/135092')
	// crawler.queueURL(host + '/Players/89401')
	// crawler.queueURL(host + '/Players/10088')
	// crawler.queueURL(host + '/Players/25814')
	// crawler.queueURL(host + '/Players/23906')
	// crawler.queueURL(host + '/Players/7989')
	// crawler.queueURL(host + '/MatchesFeed/959651/MatchCentre')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=passing&statsAccumulationType=0&teamIds=278&matchId=106219')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=offensive&statsAccumulationType=0&isCurrent=true&teamIs=278&matchId=1006219')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=defensive&statsAccumulationType=0&isCurrent=true&teamIs=71&matchId=1006219')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=offensive&statsAccumulationType=0&isCurrent=true&teamIs=71&matchId=1006219')
	// crawler.queueURL(host + '/MatchesFeed/969703/MatchCentre')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=summary&subcategory=all&statsAccumulationType=0&isCurrnt=true&teamIds=37&matchId=969703')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=passing&statsAccumulationType=0&teamIds=37&matchId=96903')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=summary&subcategory=all&statsAccumulationType=0&isCurrnt=true&teamIds=33&matchId=969706')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=defensive&statsAccumulationType=0&isCurrent=true&teamIs=33&matchId=969706')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=offensive&statsAccumulationType=0&isCurrent=true&teamIs=33&matchId=969706')
	// crawler.queueURL(host + '/MatchesFeed/969708/MatchCentre')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=passing&statsAccumulationType=0&teamIds=42&matchId=96908')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=defensive&statsAccumulationType=0&isCurrent=true&teamIs=282&matchId=969708')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=summary&subcategory=all&statsAccumulationType=0&isCurrnt=true&teamIds=110&matchId=969709')
	// crawler.queueURL(host + '/MatchesFeed/958922/MatchCentre')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=summary&subcategory=all&statsAccumulationType=0&isCurrnt=true&teamIds=25&matchId=958922')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=defensive&statsAccumulationType=0&isCurrent=true&teamIs=25&matchId=958922')
	// crawler.queueURL(host + '/StatisticsFeed/1/GetMatchCentrelayerStatistics?category=offensive&statsAccumulationType=0&isCurrent=true&teamIs=25&matchId=958922')
	// crawler.queueURL(host + '/Players/12414')
	// crawler.queueURL(host + '/Players/78089')
	// crawler.queueURL(host + '/Players/76729')
	// crawler.queueURL(host + '/Players/25094')
	// crawler.queueURL(host + '/Players/14325')
	// crawler.queueURL(host + '/Players/21814')
	// crawler.queueURL(host + '/Players/87163')
	// crawler.queueURL(host + '/Players/134328')
	// crawler.queueURL(host + '/Players/7890')
	// crawler.queueURL(host + '/Players/9563')
	// crawler.queueURL(host + '/Players/108374')
	// crawler.queueURL(host + '/Players/90349')
	// crawler.queueURL(host + '/Players/29244')
    crawler.start();
})
